name: blue_ui_app
description: A Flutter application with aesthetic blue UI and multiple pages.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  # QR code scanner
  mobile_scanner: ^3.5.4
  flutter_html: ^3.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.0

  # URL launcher to open links
  url_launcher: ^6.2.2

  # Icons
  cupertino_icons: ^1.0.6

  # Animation
  animations: ^2.0.8

  dropdown_button2: ^2.3.9
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/metaqrlogo.png

  # To add assets to your application, add an assets section:
  # assets:
  #   - images/app_logo.png

  # To add custom fonts to your application, add a fonts section:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
